name: agent
downdir: ../download
net:
    ip: 127.0.0.1
    mgntPort: 45010
    dataPort: 45011
    tls:
        cert: ../misc/server.crt
        key: ../misc/server.key
auth:
    username: gofd
    password: LFFex2mDcetFDnghcZqpz0z/zbzYhRLBj58fnAs45uc=
    factor: 802cbde8
control:
    cacheSize: 50 # unit is MB
    maxActive: 10